compile:
	javac -d classes/ src/Minesweeper.java
run: compile
	java -cp classes/ Minesweeper 10 10
run5: compile
	java -cp classes/ Minesweeper 5 5
runSeed: compile
	java -cp classes/ Minesweeper ./seed1.txt