compile:
	javac -d classes/ -cp ../../../../profs/mehdi/cs1302/junit-example/junit-4.12.jar src/edu/uga/cs1302/*/*.java
test: 
	java -cp classes/:../../../../profs/mehdi/cs1302/junit-example/junit-4.12.jar:../../../../profs/mehdi/cs1302/junit-example/hamcrest-core-1.3.jar org.junit.runner.JUnitCore edu.uga.cs1302.test.MyStringTester